
/* James Bond ha aprendido SQL :-) */

--Variables de filtro setear a las fechas deseadas
declare @fechaInicioFiltro datetime
declare @fechaFinFiltro datetime
declare @usuarioFiltro varchar(max)

set @fechaInicioFiltro = '2026-03-13'
set @fechaFinFiltro = getdate()+1
set @usuarioFiltro = '%'	--poner % si no se quiere filtrar por usuario

--Variables auxiliares
declare @sql nvarchar(max)
declare @cursorIdPkFieldAux varchar(750)
declare @camposFormateados nvarchar(max)
declare @campoAux nvarchar(max)
declare @tipoDatoCampoAux varchar(255)
declare @sentenciaReplace nvarchar(max)
declare @cursorValoresPkFieldAux varchar(750)
declare @vWhere nvarchar(max)
declare @valorAux nvarchar(max)

--Tabla temporal para guardar y mostrar los resultados
create table #objetosTocados (
	ID_ORGANIZATION nvarchar(4) collate database_default NOT NULL DEFAULT ('0000'),
	ID_TABLA nvarchar(30) collate database_default NOT NULL,
	PK1 nvarchar(400) collate database_default NOT NULL,
	FECHA datetime NOT NULL,
	ID_CLASS nvarchar(50) collate database_default NULL,
	USUARIO nvarchar(30) collate database_default NULL,
	TIPO_TRANSFER nvarchar(1) collate database_default NULL,
	ID_APPROLE nvarchar(30) collate database_default NULL,
	ID_SECUSER nvarchar(30) collate database_default NULL,
	DT_LAST_UPDATE datetime NULL,
	ID_REAL_OBJECT_LECTURA nvarchar(50) collate database_default NULL,
	CAMPOS_PK1 nvarchar(400) collate database_default NOT NULL,
	SENTENCE nvarchar(max) collate database_default NULL,

	PRIMARY KEY (ID_TABLA, PK1,	FECHA, ID_ORGANIZATION)
) 

--Creamos la tabla donde pondremos las tablas de las que queremos escanear
DECLARE @TABLAS_ESCANEAR TABLE (
	ID_ORGANIZATION nvarchar(4) NOT NULL,
	ID_CLASS nvarchar(50) NOT NULL,
	ID_REAL_OBJECT nvarchar(50) NOT NULL,
	ID_PK_FIELD1 nvarchar(400) NULL,
	ID_APPROLE nvarchar(30) NULL,
	ID_SECUSER nvarchar(30) NULL,
	DT_LAST_UPDATE datetime NULL,
	TIPO_TRANSFER nvarchar(1) NULL,
	ID_REAL_OBJECT_LECTURA nvarchar(50) NULL,
	
	PRIMARY KEY (ID_CLASS, ID_REAL_OBJECT, ID_ORGANIZATION)
)


--Creamos la tabla donde pondremos las clases que queremos excluir
DECLARE @CLASES_EXCLUIDAS TABLE (
	ID_ORGANIZATION nvarchar(4) NOT NULL DEFAULT ('0000'),
	ID_CLASS nvarchar(50) NOT NULL,
	ID_APPROLE nvarchar(30) NULL,
	ID_SECUSER nvarchar(30) NULL,
	DT_LAST_UPDATE datetime NULL,
	EXCLUIDO nvarchar(1) NULL,
	
	PRIMARY KEY (ID_CLASS, ID_ORGANIZATION)
)

--Creamos la tabla donde pondremos los objetos modificados agrupados 
DECLARE @objetosModificadosAgrupados TABLE (
	
	ID_CLASS nvarchar(50) NOT NULL,
	ID_TABLA nvarchar(50) NOT NULL,
	PK1 nvarchar(400) NOT NULL,
	FECHA datetime NOT NULL,
	TIPO_TRANSFER nvarchar(1) NOT NULL,
	USUARIO nvarchar(30) NOT NULL,
	CAMPOS_PK1 nvarchar(400) NOT NULL,
	
	PRIMARY KEY (ID_CLASS, ID_TABLA, USUARIO, PK1, TIPO_TRANSFER, FECHA)

	--ID_CLASS as idClass, ID_TABLA as idObjeto, PK1 as valorObjeto, CONVERT(varchar,MAX(FECHA),23) as fecha, TIPO_TRANSFER as tipoTransfer, USUARIO as usuario, CAMPOS_PK1 as camposObjeto
)

--Creamos la tabla donde pondremos el detalle de los elementos que se se han modificado
DECLARE @itemsDetalle TABLE (

	ID_CLASS nvarchar(50) collate database_default NOT NULL,
	ID_OBJETO nvarchar(100) collate database_default NOT NULL,
	ID_ITEM nvarchar(100) collate database_default NOT NULL,
	TIPO_ITEM nvarchar(30) collate database_default NULL,
	USUARIO nvarchar(30) collate database_default NULL,
	FECHA datetime NOT NULL,
	
	PRIMARY KEY (ID_CLASS, ID_OBJETO, ID_ITEM)
)

--Variables para el cursor que recorrerá la tabla @TABLAS_ESCANEAR
declare @cursorIdOrganization varchar(4)
declare @cursorIdClass nvarchar(50)
declare @cursorIdRealObject nvarchar(50)
declare @cursorIdPkField1 nvarchar(max)
declare @cursorIdAppRole nvarchar(30)
declare @cursorIdSecuser nvarchar(30)
declare @cursorDtLastUpdate datetime
declare @cursorTipoTransfer nvarchar(1)
declare @cursorIdRealObjectLectura nvarchar(50)
declare @cursorValoresPkField1 nvarchar(max)


/****************************************************************************
			INSERCION DE DATOS EN LAS TABLAS A ESCANEAR Y A EXCLUIR
****************************************************************************/
--OBJETOS LOGICOS
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','APP_ROLE','M4RSC_APPROLE','ID_APP_ROLE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','APP_ROLE','M4RSC_ROLE_ORG','ID_APP_ROLE_USED',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','APP_ROLE','M4RSC_SEC_PR_OPT','ID_APP_ROLE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','APP_USER','M4RSC_APP_USR_ROLE','ID_APP_USR',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','APP_USER','M4RSC_APPUSER','ID_APP_USER',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','APP_USER','M4RSC_USR_TYPES','ID_USR_TYPE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BP CATEGORY','M4RBP_BP_CATEGORY','ID_CATEGORY',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BP CATEGORY','M4RBP_CATEGORIES','ID_CATEGORY',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP__PAR_DINAMIC','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_CODE','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_CODE_ALIAS','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_DEF','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_EXE_CODE','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_PAR_DEF','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_PARAM_DEF','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_PARAM_DEFAUL','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_PARAM_FLOW','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','BUSINESS PROCESS','M4RBP_STRUCT','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','CASE MODULE','M4RDD_CASE_MODULES','ID_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','CASE MODULE','M4RDD_CMOD_EXT_PTS','ID_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','CASE MODULE','M4RDD_CMOD_OBJS','ID_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','CASE MODULE','M4RDD_CMOD_RELS','ID_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','CATEGORY','M4RPT_THESAURUS','ID_CATEGORY',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','COLOR','M4RRP_COLORS','ID_COLOR',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','DMD','M4RCH_DMD_COMPNTS','ID_DMD',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','DMD','M4RCH_DMD_GROUPS','ID_DMD',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','DMD','M4RCH_DMD_GRP_CMP','ID_DMD',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','DMD','M4RCH_DMDS','ID_DMD',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','DMD','M4RCH_VALUES','ID_DMD',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','DMD','M4RCH_VALUES_GRPS','ID_DMD',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT','M4REV_DEST','ID_EVENT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT','M4REV_EVENT','ID_EVENT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT','M4REV_ORIG','ID_EVENT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT','M4REV_PARAM','ID_EVENT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT','M4REV_PARAM_DEST','ID_EVENT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT','M4REV_PARAM_ORIG','ID_EVENT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENT MODULE','M4REV_LU_MODULES','ID_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXECUTION_PROJECTS','M4RDM_OS_PROJ_MEMS','ID_PROJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXECUTION_PROJECTS','M4RDM_OS_PROJ_TREE','ID_PROJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXECUTION_PROJECTS','M4RDM_OS_PROJECTS','ID_PROJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXTENDED FUNCTION','M4RDC_EXT_FUNC_ARG','ID_FUNCTION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXTENDED FUNCTION','M4RDC_EXTENDED_FUN','ID_FUNCTION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXTENDED FUNCTION','M4RDC_FUN_ARGS_REL','ID_FUNCTION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXTENDED FUNCTION','M4RDC_FUNCTION_REL','ID_FUNCTION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXTENDED TYPE','M4RDC_EXT_TPS_TRAN','ID_TYPE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FILTER','M4RDC_FILTERS','ID_FILTER',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EXTENDED TYPE','M4RDC_EXTENDED_TPS','ID_TYPE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FORMAT','M4RPT_FORMATS','ID_FORMAT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FUNC MODULE ERRORS','M4RSY_ERROR_MSGS','ID_FUN_MOD_NUM',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FUNC MODULE ERRORS','M4RSY_FUN_MODULES','ID_FUN_MOD_NUM',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FUNCTIONAL MODULE','M4RSY_FUN_MOD_OBJ','ID_FUN_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FUNCTIONAL MODULE','M4RSY_FUN_MODULES','ID_FUN_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','FUNCTIONAL MODULE','M4RSY_FUN_SMODULES','ID_FUN_MODULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','IMPORT','M4RIM_FIELDSIM','ID_COD_IMP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','IMPORT','M4RIM_IMPORTS','ID_COD_IMP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','IMPORT GROUP','M4RIM_GROUPIM','ID_COD_GROUP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','IMPORT GROUP','M4RIM_RELIM','ID_COD_GROUP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JAVA OBJECT','M4RJV_JAR_DEF','ID_JAR',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JAVA OBJECT','M4RJV_JAR_VER_FILE','ID_JAR',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_DOC_EXE','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_JOB_DEF','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_JOB_EXE','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_JOB_PARAMS','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_JOBGROUP_EXE','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_JOBGRP_DEF','ID_JOB_GROUP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_PARAM_EXEC','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_PARAM_FLOW','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','JOB GROUP','M4RJS_RESOURCE_EXE','ID_JOB_GROUP_DEF',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RAU_LOBJ_OPE','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RCH_CAR_FILTERS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RCH_CAR_FLTR_FLD','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RCH_VALUES','ID_OBJECT_VALUES',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RCH_YTD_OBJECTS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_FIELDS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_FIELDS_TRANS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_INDEX','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_INDEX_COLS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_LOGIC_OBJECT','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_REAL_FIELDS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_REAL_INDEX','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_REAL_OBJECTS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_REL_FM_SBREC','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_RELATIONS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_RLTION_FLDS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_SEC_FIELDS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_TH_PLANA','ID_HIJA',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDC_VIEW_CODE','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_FIELDS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_FIELDS_TRANS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_INDEX','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_INDEX_COLS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_LOGIC_OBJECT','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_REL_FM_SBREC','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_RELATIONS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_TH_PLANA','ID_HIJA',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','LOGICAL TABLE','M4RDD_VIEW_CODE','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','MENU OPTION','M4RMN_ARGUMENTS','ID_MENU',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','MENU OPTION','M4RMN_OPTIONS','ID_MENU',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','MENU OPTION','M4RMN_TREE','ID_MENU',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_ALIAS_RES','ID_ALIAS_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_BO_MET_ARG','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_BO_METHOD','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_CONCEPT_NODE','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_CONCTOR_ARG','ID_ITEM_CONCTOR_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_CONCTOR_ITEM','ID_ITEM_CONCTOR_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_CONCTOR_PAR','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_CONNECTORS','ID_CONNECTOR_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_DISABLEDITEM','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_FILTER_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_FILTER_PRED','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_FILTERS','ID_FILTER_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_INDEX','ID_INDEX_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_INDEX_ITEM','ID_INDEX_ITEM_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_ITEM_CSDESC','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_ITEM_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_MD_VERSION','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_NODE_FILTER','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_NODE_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_NODE_MIG','ID_T3_MIG',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_NODES','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_OVERWRITE_NO','ID_NODE_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_PAYROLL_ITEM','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_PI_TAGS','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_PICOMPONENTS','ID_COMPONENT_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_QUERY_USER','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_T3_ALIAS_RES','ID_ALIAS_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_T3_CONN_ITEM','ID_LIST_ITEM_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_T3_CONNTORS','ID_LIST_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_T3_INHERIT','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_T3_MIG','ID_T3_MIG',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RCH_T3S','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RFE_NODE_PROPS','ID_CHANNEL',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RFE_PAT_REL','ID_CHANNEL',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RPM_PAYROLL_MENU','ID_T3_EXE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RPM_PAYROLL_T3S','ID_T3_EXE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RRP_NODE_GROUPS','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RRP_NODES_IN_GRP','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RRP_VISIBLE_NODE','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RWP_NDS_AC_READ','ID_T3_PAYROLL',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RWP_NODES_AC_CLC','ID_NODE_AC_CALC_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RWP_NODES_CALC','ID_T3_PAYROLL',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RWP_NODES_CALC_O','ID_T3_PAYROLL',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RWP_NODES_FILTER','ID_ITEM_FILTER_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RXM_ITEM_MAP','ID_META4OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RXM_M4OBJECT_MAP','ID_META4OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','M4RXM_NODE_MAP','ID_META4OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','META4OBJECT','SPR_DIN_OBJECTS','ID_T3_I',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RAU_PAR_AUDT_LOB','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_CHANNEL_DEP','ID_RULE_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_CONCEPT_NODE','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_CONCEPTS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_CONCEPTS_OWR','ID_CONCEPT_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_EXTERNAL_DEP','ID_RULE_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_INTERNAL_DEP','ID_RULE_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_ITEM_ARGS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_ITEM_PI','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_ITEMS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_ITEMS_OWR','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_LU_EXE_GROUP','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_QRY_LETR_DEP','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_RULE_SENTENC','ID_RULE_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_RULES','ID_RULE_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TAGS','ID_TAG_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TI_ALIAS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TI_CONN_ITM','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TI_FILTERS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TI_MASK','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TI_MD_VER','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TI_T3_ALIAS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TIS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TIS_INHERIT','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TOTAL_REF','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RCH_TOTALS','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','NODE STRUCTURE','M4RXM_ITEM_MAP','ID_TI',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PAGE','M4RTC_ITEM_ARG_DEP','ID_PAGE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PAGE','M4RTC_ITEMS_DEP','ID_PAGE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PAGE','M4RTC_META4OBJ_DEP','ID_PAGE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PAGE','M4RTC_NODES_DEP','ID_PAGE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PAGE','M4RTC_PAGES','ID_PAGE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PI TEMPLATES','M4RCH_PI_IMP_TMPL','ID_TEMPLATE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PI TEMPLATES','M4RCH_PI_TEMPLATES','ID_TEMPLATE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PI TEMPLATES','M4RCH_PI_TMPL_COMP','ID_TEMPLATE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RCH_MD_VERSION','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4ROBOT_LOG','ID_PRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_DOCU_PRES','IDPRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_PRES_INHERIT','ID_PRES',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_PRES_STYLE','ID_PRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_PRESENT_PKG','ID_PRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_PRESENT_USE','ID_PRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_PRESENTATION','ID_PRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','M4RPT_UNIT_GROUP','ID_PRESENTATION',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PRESENTATION','SPR_DIN_PRESENTS','ID_PRESENTATION_I',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PROJECT_TASK_PARAM','M4RBP__PAR_DINAMIC','ID',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','PROJECT_TASK_PARAM','M4RDM_OS_PROJ_MEMS','ID_INSTANCE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_CNT_FL_ND_DP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_CNT_FLD_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_CNT_NODE_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_CONTAI_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_EMISSION','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_EXECUTION_TP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_FAMILY_SECTS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_FILE_GRAPH','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_LONG_EXPRES','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_PAG_FLD_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_PAG_FLD_PROP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_PAGE_PROPS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_PG_FLD_ND_DP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_CODE','ID_REPORT_ODBC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_COLOR','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_FONTS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_PAGS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_PROP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_SECTS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORT_STR','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPORTS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPRT_FRMTS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_REPRTS_ODBC','ID_REPORT_ODBC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_RPT_CT','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_RPT_CT_PROPS','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_RPT_JT_CLNT','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_RPT_NODE_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_RPT_SEC_PROP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_SC_CNTFLDPRP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_SEC_CON_PRO','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_SECT_CON_FLD','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_SECT_CONTAIN','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_SECTION_DEP','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','REPORT','M4RRP_SECTION_NODE','ID_REPORT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','RSM','M4RSC_RSM','ID_RSM',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','RULE TEMPLATE','M4RCH_PI_TMPL_RULE','ID_TMPL_RULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SCENARIO','M4RDC_GR_OB_PA_REL','ID_GROUP_OBJECTS',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SCENARIO','M4RDC_GR_PA_RL_FLD','ID_GROUP_OBJECTS',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SCENARIO','M4RDC_GROUP_OBJS','ID_GROUP_OBJECTS',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SCENARIO','M4RDC_GRP_OBJ_PATH','ID_GROUP_OBJECTS',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY BP','M4RBP_APPROLE','ID_BP',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY LT','M4RDC_SEC_FIELDS','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY LT','M4RDC_SEC_LOBJ','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY LT','M4RDC_SEC_LOBJ_FIL','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY LT','M4RDC_SEC_RELATION','ID_OBJECT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_FILTER_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_ITEM_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_MD_VERSION','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_NODE_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_T3_CON_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_T3_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_T3_RSM','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SECURITY M4O','M4RCH_TI_MASK','ID_T3',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','SENTENCE','M4RCH_SENTENCES','ID_SENTENCE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','TEMPLATE FILES','M4RCH_TEMPL_DOC','ID_TEMPLATE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','TEMPLATE FILES','SCH_TEMPLATE_FILES','ID_TEMPLATE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','UNIT','M4RPT_UNIT','ID_UNIT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','UNIT','M4RPT_UNIT_DESC','ID_UNIT',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','USE','M4RPT_USE','ID_USE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','USE','M4RPT_USE_DESC','ID_USE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW INSTANCE','M4RWF_BPO','ID_BPO',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW INSTANCE','M4RWF_EV_EXPECTED','ID_BPO',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW INSTANCE','M4RWF_INST_DATA','ID_BPO',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW INSTANCE','M4RWF_INST_TASK','ID_BPO',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW INSTANCE','M4RWF_SUBBPO','ID_BPO',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW INSTANCE','M4RWF_WORKITEM','ID_BPO',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_ASSIGNEDROLE','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_BPC','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_DATADEF','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_EVENTASSOC','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_J_SBPC_MAP','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_JOINED_SBPC','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_RL_PARMAP','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_STATE','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_STATE_RULE','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_SUBBPC','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_SUBBPC_MAP','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_TASK','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_TASK_PARAM','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_TRANSCANCEL','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_TRANSITION','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW PROCESS','M4RWF_XTRAPOINT','ID_BPC',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW RULE','M4RRL_DEF','ID_RULE',NULL,NULL,NULL,'L',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','WORKFLOW RULE','M4RRL_PARAM','ID_RULE',NULL,NULL,NULL,'L',NULL)


------REPLACES
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENTOS','M4EE_CONFIGURACION','ID',NULL,NULL,NULL,'R',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENTOS','M4EE_ITEMS_INCLUIDOS_JSON','ID',NULL,NULL,NULL,'R',NULL)
INSERT INTO @TABLAS_ESCANEAR (ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, TIPO_TRANSFER, ID_REAL_OBJECT_LECTURA) VALUES ('0000','EVENTOS','M4TMC_TAREAS','ID_TAREA',NULL,NULL,NULL,'R',NULL)


------Esto por si queremos excluir alguna clase 
INSERT INTO @CLASES_EXCLUIDAS (ID_ORGANIZATION, ID_CLASS, ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, EXCLUIDO) VALUES ('0000','APP_USER','M4ADM','M4ADM',GETDATE(),'1')


/******************************************************
			OBTENCION DE OBJETOS MODIFICADOS
******************************************************/

--select de los datos que usaremos en el cursor
declare CursorClassMember
cursor for 
	SELECT ID_ORGANIZATION, ID_CLASS, ID_REAL_OBJECT, ID_PK_FIELD1, 
	ID_APPROLE, ID_SECUSER, DT_LAST_UPDATE, 
	TIPO_TRANSFER, IsNull(ID_REAL_OBJECT_LECTURA,ID_REAL_OBJECT) 
	FROM @TABLAS_ESCANEAR cl
	WHERE NOT EXISTS (
		SELECT 1 FROM @CLASES_EXCLUIDAS excl
		WHERE cl.ID_CLASS = excl.ID_CLASS
		AND excl.EXCLUIDO = 1
	)


open CursorClassMember

--Volcamos el primer registro del cursor a las variables que usaremos
fetch from CursorClassMember into @cursorIdOrganization, @cursorIdClass, @cursorIdRealObject, @cursorIdPkField1, @cursorIdAppRole, @cursorIdSecuser, @cursorDtLastUpdate, @cursorTipoTransfer, @cursorIdRealObjectLectura

while @@fetch_status=0
begin
	--Descomentar para ver los datos del cursor
	--SELECT @cursorIdOrganization, @cursorIdClass, @cursorIdRealObject, @cursorIdPkField1, @cursorIdAppRole, @cursorIdSecuser, @cursorDtLastUpdate, @cursorTipoTransfer, @cursorIdRealObjectLectura
	
	--Si los campos de la PK tienen un | es porque la PK esta compuesta por varios campos y tenemos que separarlos
	If CHARINDEX('|',@cursorIdPkField1) = 0 
	Begin
		set @camposFormateados = @cursorIdPkField1	--Si no tiene | simplemente toma el valor del campo
	End
	Else
	Begin
		-- Procesamos los distintos campos y los concatenaremos en uno solo
		set @cursorIdPkFieldAux = @cursorIdPkField1
		set @camposFormateados = ''
		WHILE CHARINDEX('|',@cursorIdPkFieldAux,0) <> 0 
		begin
			--Guardamos el campo que estamos procesando
			set @campoAux = RTRIM(LTRIM(SUBSTRING(@cursorIdPkFieldAux,1,CHARINDEX('|',@cursorIdPkFieldAux,0)-1)))

			--Obtenemos el tipo de dato del campo
			select @tipoDatoCampoAux = data_type from INFORMATION_SCHEMA.COLUMNS where table_name=@cursorIdRealObjectLectura and column_name = @campoAux
			
			--Concantemamos el campo que estamos tratando
			set @camposFormateados = @camposFormateados + 'convert(varchar(1500), ' + @campoAux + ') + ''|'' + '

			--Eliminamos el campo tratado de la cadena
			set @cursorIdPkFieldAux=RTRIM(LTRIM(SUBSTRING(@cursorIdPkFieldAux,CHARINDEX('|',@cursorIdPkFieldAux,0)+1,LEN(@cursorIdPkFieldAux))))
		end
		--Al salir del bucle aun falta un campo por tratar así que lo añadimos a la cadena
		set @camposFormateados = @camposFormateados + 'convert(varchar(1500), ' + @cursorIdPkFieldAux + ')'
	End
	
	--select @camposFormateados, @cursorIdRealObjectLectura, @cursorIdPkField1
	set @sql = 'insert into #objetosTocados (ID_ORGANIZATION, ID_TABLA, PK1, FECHA, USUARIO, ID_CLASS, TIPO_TRANSFER, CAMPOS_PK1)'
    set @sql = @sql + ' select distinct ''0000'', ''' + @cursorIdRealObject + ''',' + @camposFormateados + ', '
    set @sql = @sql + ' ISNULL(DATEADD(MILLISECOND, -DATEPART(MILLISECOND , DT_LAST_UPDATE ), DT_LAST_UPDATE ),''18000101''), '
    set @sql = @sql + ' ID_SECUSER, ''' + @cursorIdClass + ''', ''' + @cursorTipoTransfer + ''',''' + @cursorIdPkField1 + ''' from '
    set @sql = @sql + @cursorIdRealObjectLectura
  	set @sql = @sql + ' WHERE DT_LAST_UPDATE >= @fechaInicioFiltro'
	set @sql = @sql + ' AND DT_LAST_UPDATE <= @fechaFinFiltro + 1' --Sumamos un dia a la fecha de fin porque los campos son fecha y hora
    
	
	EXEC sp_executesql @sql, N'@fechaInicioFiltro datetime, @fechaFinFiltro datetime',@fechaInicioFiltro,@fechaFinFiltro
	
	--Volcamos el siguiente registro del cursor a las variables que usaremos
	fetch from CursorClassMember into @cursorIdOrganization, @cursorIdClass, @cursorIdRealObject, @cursorIdPkField1, @cursorIdAppRole, @cursorIdSecuser, @cursorDtLastUpdate, @cursorTipoTransfer, @cursorIdRealObjectLectura
end

close CursorClassMember
deallocate CursorClassMember

--Descomentar si se quiere ver los datos puros de objetos modificados
--SELECT * FROM #objetosTocados


--insertamos los objetos modificados agrupados por maxima fecha 
INSERT INTO @objetosModificadosAgrupados
SELECT ID_CLASS as idClass, ID_TABLA as idObjeto, PK1 as valorObjeto, CONVERT(varchar,MAX(FECHA),23) as fecha, TIPO_TRANSFER as tipoTransfer, USUARIO as usuario, CAMPOS_PK1 as camposObjeto
FROM #objetosTocados 
WHERE TIPO_TRANSFER = 'R'
AND USUARIO LIKE @usuarioFiltro
AND PK1 not like 'tmp%'	--Quitamos las presentaciones temporales
AND PK1 NOT LIKE '%#'	--Quitamos las tablas traducidas #
GROUP BY ID_CLASS, ID_TABLA, PK1, TIPO_TRANSFER, USUARIO, CAMPOS_PK1
UNION
SELECT ID_CLASS as idClass, MAX(ID_TABLA) as idObjeto, PK1 as valorObjeto, CONVERT(varchar,MAX(FECHA),23) as fecha, TIPO_TRANSFER as tipoTransfer, MAX(USUARIO) as usuario, MAX(CAMPOS_PK1) as camposObjeto
FROM #objetosTocados 
WHERE TIPO_TRANSFER <> 'R'
AND USUARIO LIKE @usuarioFiltro
AND PK1 not like 'tmp%'	--Quitamos las presentaciones temporales
AND PK1 NOT LIKE '%#'	--Quitamos las tablas traducidas #
GROUP BY ID_CLASS, PK1, TIPO_TRANSFER

--Insertamos el detalle de los items
INSERT INTO @itemsDetalle 
SELECT DISTINCT  OBJ.ID_CLASS, A.ID_TI, A.ID_ITEM, B.N_ITEM_TPESP, A.ID_SECUSER, CONVERT(varchar,A.DT_LAST_UPDATE,23) AS fechaDetalle
from #objetosTocados OBJ
INNER JOIN 
	(SELECT ID_CLASS, PK1, MAX(FECHA) AS FECHA
		FROM #objetosTocados 
		WHERE TIPO_TRANSFER <> 'R'
		AND USUARIO LIKE @usuarioFiltro
		AND ID_CLASS = 'NODE STRUCTURE'
		AND PK1 not like 'tmp%'	--Quitamos las presentaciones temporales
		AND PK1 NOT LIKE '%#'	--Quitamos las tablas traducidas #
		GROUP BY ID_CLASS, PK1) ULTMOD
ON OBJ.ID_CLASS = ULTMOD.ID_CLASS
AND OBJ.PK1 = ULTMOD.PK1
AND OBJ.FECHA = ULTMOD.FECHA
INNER JOIN M4RCH_ITEMS A on A.ID_TI = OBJ.PK1
INNER JOIN M4RCH_LU_ITEM_TP B ON B.ID_ITEM_TYPE = A.ID_ITEM_TYPE
where 
A.DT_LAST_UPDATE >= @fechaInicioFiltro 
AND A.DT_LAST_UPDATE <= @fechaFinFiltro + 1
UNION
SELECT DISTINCT OBJ.ID_CLASS, R.ID_RULE_TI, R.ID_ITEM, B.N_ITEM_TPESP, R.ID_SECUSER, CONVERT(varchar,R.DT_LAST_UPDATE,23) AS fechaDetalle
 from #objetosTocados OBJ
INNER JOIN 
	(SELECT ID_CLASS, PK1, MAX(FECHA) AS FECHA
		FROM #objetosTocados 
		WHERE TIPO_TRANSFER <> 'R'
		AND USUARIO LIKE @usuarioFiltro
		AND ID_CLASS = 'NODE STRUCTURE'
		AND PK1 not like 'tmp%'	--Quitamos las presentaciones temporales
		AND PK1 NOT LIKE '%#'	--Quitamos las tablas traducidas #
		GROUP BY ID_CLASS, PK1) ULTMOD
ON OBJ.ID_CLASS = ULTMOD.ID_CLASS
AND OBJ.PK1 = ULTMOD.PK1
AND OBJ.FECHA = ULTMOD.FECHA
INNER JOIN M4RCH_RULES R ON R.ID_RULE_TI = OBJ.PK1
INNER JOIN M4RCH_ITEMS I ON (I.ID_TI = R.ID_TI AND I.ID_ITEM = R.ID_ITEM) 
INNER JOIN M4RCH_LU_ITEM_TP B ON (B.ID_ITEM_TYPE= I.ID_ITEM_TYPE )
where R.ID_RULE_TI <> R.ID_TI
AND R.DT_LAST_UPDATE >= @fechaInicioFiltro 
AND R.DT_LAST_UPDATE <= @fechaFinFiltro + 1




/****************************************
			RESULTADOS
****************************************/

--Json con las tablas escaneadas
select t.ID_REAL_OBJECT as idTabla
,campos.COLUMN_NAME as 'idCampo'
,CASE 
	WHEN campos.DATA_TYPE IN ('int', 'float', 'double', 'numeric') then 'numeric'
	WHEN campos.DATA_TYPE IN ('datetime') then 'datetime'
	ELSE 'string'
END as 'idTipoCampo'
from @TABLAS_ESCANEAR t 
inner join INFORMATION_SCHEMA.COLUMNS campos on (campos.table_name = t.ID_REAL_OBJECT)
order by t.ID_REAL_OBJECT
FOR JSON AUTO, root ('tablas'), INCLUDE_NULL_VALUES 


--Json con los objetos modificados
SELECT ID_CLASS as idClass, ID_TABLA as idObjeto, PK1 as valorObjeto,CONVERT(varchar,FECHA,23) as fecha, TIPO_TRANSFER as tipoTransfer, USUARIO as usuario, CAMPOS_PK1 as camposObjeto
FROM @objetosModificadosAgrupados
FOR JSON AUTO, root ('objetosModificados')

--Json con el detalle de los items de las estructuras de nodo
SELECT detalleItems.ID_CLASS as idClassDetalle, detalleItems.ID_OBJETO as idObjetoDetalle, detalleItems.ID_ITEM as idItemDetalle, detalleItems.USUARIO as usuarioDetalle, CONVERT(varchar,detalleItems.FECHA,23) as fechaDetalle
FROM @itemsDetalle detalleItems
FOR JSON AUTO, root ('detalleItems')

--Borramos las tablas temporales
drop table #objetosTocados
